
[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -DCONFIG_LOG_MAXIMUM_LEVEL_VERBOSE=y
    -DCONFIG_LOG_MAXIMUM_LEVEL=5
lib_deps = 
    FastLED
